#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES ───────────────────────────────────────────────────────────────────
#
# Creates the private S3 bucket that applicant payslips are stored in, and a
# user scoped to nothing else. The app serves these files through its own
# tokenised endpoint, so the bucket itself stays entirely closed - no public
# access, no presigned links handed to third parties.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=6
REGION="ap-southeast-1"

banner "Applicant documents bucket (crawfort-dev)"

# ── 1. The right account ──────────────────────────────────────────────────
stage "Sign in to the crawfort-dev account"
say "Everything below lands in whichever account this browser is signed in to,"
say "so it is worth being sure before the first click."
open_url "https://ap-southeast-1.console.aws.amazon.com/console/home?region=$REGION"
step "Check the account name in the top-right menu reads crawfort-dev."
step "Check the region selector, also top-right, reads Singapore ap-southeast-1."
confirm "Signed in to crawfort-dev, region Singapore?" || { echo "  Stopping."; exit 1; }

# ── 2. The bucket ─────────────────────────────────────────────────────────
stage "Create the bucket"
say "Payslips carry NRIC, addresses and bank details, so this bucket is private"
say "and stays private. The app reads from it server-side and streams the file"
say "to whoever is allowed to see it."
open_url "https://$REGION.console.aws.amazon.com/s3/bucket/create?region=$REGION"
step "Bucket name: crawfort-applicant-documents-dev"
step "   (S3 names are global - if taken, add your initials and use that below.)"
step "AWS Region: Asia Pacific (Singapore) ap-southeast-1"
step "Block Public Access: leave ALL FOUR boxes ticked. This is the important one."
step "Bucket Versioning: Enable - so a re-upload cannot destroy the original."
step "Default encryption: SSE-S3 (Amazon S3 managed keys) is enough here."
step "Click Create bucket."
ask DOCUMENTS_S3_BUCKET "Bucket name you created:"
[[ -n "$DOCUMENTS_S3_BUCKET" ]] || { echo "  A bucket name is required."; exit 1; }
write_env DOCUMENTS_S3_BUCKET "$DOCUMENTS_S3_BUCKET"
write_env DOCUMENTS_S3_REGION "$REGION"

# ── 3. Retention ──────────────────────────────────────────────────────────
stage "Set a retention rule"
say "Singapore moneylending records are kept for five years after the loan ends."
say "Nothing is deleted automatically inside that window; this rule only moves"
say "older files to cheaper storage so the bill does not grow forever."
open_url "https://$REGION.console.aws.amazon.com/s3/management/$DOCUMENTS_S3_BUCKET/lifecycle/create?region=$REGION"
step "Rule name: archive-old-documents"
step "Choose: Apply to all objects in the bucket, and tick the acknowledgement."
step "Tick 'Move current versions of objects between storage classes'."
step "   Standard-IA after 90 days, then Glacier Flexible Retrieval after 365."
step "Do NOT add an expiration rule. These are credit records."
step "Click Create rule."
pause

# ── 4. A permission that reaches nothing else ─────────────────────────────
stage "Create the IAM policy"
say "Scoped to this one bucket, and to reading and writing objects in it -"
say "so a leaked key cannot touch anything else in the account."
open_url "https://console.aws.amazon.com/iam/home#/policies\$new?step=edit"
step "Click the JSON tab and replace everything with:"
cat <<POLICY

  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "ReadWriteApplicantDocuments",
        "Effect": "Allow",
        "Action": ["s3:PutObject", "s3:GetObject", "s3:DeleteObject"],
        "Resource": "arn:aws:s3:::$DOCUMENTS_S3_BUCKET/*"
      },
      {
        "Sid": "ListOwnBucketOnly",
        "Effect": "Allow",
        "Action": ["s3:ListBucket"],
        "Resource": "arn:aws:s3:::$DOCUMENTS_S3_BUCKET"
      }
    ]
  }

POLICY
step "Next, name it: crawfort-applicant-documents-rw"
step "Click Create policy."
pause

# ── 5. The user and its keys ──────────────────────────────────────────────
stage "Create the user and access keys"
say "The secret key is shown once and never again, so keep this page open"
say "until both values are pasted below."
open_url "https://console.aws.amazon.com/iam/home#/users/create"
step "User name: crawfort-documents-dev"
step "Do NOT tick 'Provide user access to the AWS Management Console'."
step "Next → Attach policies directly → search crawfort-applicant-documents-rw → tick it."
step "Next → Create user."
step "Open the new user → Security credentials → Create access key."
step "Use case: 'Application running outside AWS'. Confirm, then Create."
ask_secret AWS_ACCESS_KEY_ID "Paste the Access key ID:"
ask_secret AWS_SECRET_ACCESS_KEY "Paste the Secret access key:"
[[ -n "$AWS_ACCESS_KEY_ID" && -n "$AWS_SECRET_ACCESS_KEY" ]] || { echo "  Both keys are required."; exit 1; }
write_env AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
write_env AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"

# ── 6. Prove it works ─────────────────────────────────────────────────────
stage "Sign the document links, and check the whole thing works"
say "The app hands Ascend a link on our own domain rather than a raw S3 URL,"
say "so the link does not expire and the bucket is never exposed. This secret"
say "signs those links; it is generated here and needs no AWS involvement."
DOCUMENTS_URL_SECRET=$(openssl rand -hex 32)
write_env DOCUMENTS_URL_SECRET "$DOCUMENTS_URL_SECRET"

say ""
say "Now checking the credentials can actually reach the bucket..."
if AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
   AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
   AWS_MAX_ATTEMPTS=2 \
   aws s3 ls "s3://$DOCUMENTS_S3_BUCKET/" --region "$REGION" >/dev/null 2>&1; then
  printf '  %s✓%s the bucket is reachable with these keys\n' "$GREEN" "$RESET"
else
  warn "could not list the bucket with those keys"
  say "  New IAM keys can take a few seconds to become active - try again shortly:"
  say "    aws s3 ls s3://$DOCUMENTS_S3_BUCKET/ --region $REGION"
  say "  If it keeps failing, the policy is probably not attached to the user."
fi

say ""
say "Last step, and it is yours: add the same four values to Vercel"
say "(Settings → Environment Variables → Preview), then redeploy."
say "  DOCUMENTS_S3_BUCKET  DOCUMENTS_S3_REGION"
say "  AWS_ACCESS_KEY_ID    AWS_SECRET_ACCESS_KEY    DOCUMENTS_URL_SECRET"
pause

finish
