#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Singpass credentials are local-only; .env.local is gitignored.
ENV_FILE=".env.local"

SDP_URL="https://developer.singpass.gov.sg"
JWKS_FILE="singpass-jwks.public.json"

# The ten Myinfo attributes lib/myinfo.ts actually maps into the loan form.
# Requesting more than this means collecting data we never read, which the
# Singpass reviewers will ask you to justify.
DEFAULT_SCOPES="openid uinfin name dob email mobileno regadd residentialstatus marital noahistory cpfcontributions"

banner "Singpass FAPI 2.0 (Myinfo v5) setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Generate your signing and encryption keys"
say "Singpass needs two EC P-256 key pairs: one to sign client assertions,"
say "one to decrypt the ID token and userinfo response."
say ""

REGENERATE=yes
if grep -qE '^SINGPASS_SIG_PRIVATE_JWK=' "$ENV_FILE" 2>/dev/null; then
  warn "Keys already exist in $ENV_FILE."
  say "Regenerating gives them new kids, so the JWKS registered in the SDP"
  say "would stop matching until you paste the new one in."
  confirm "Generate a NEW pair of keys anyway?" || REGENERATE=no
fi

if [[ "$REGENERATE" == "yes" ]]; then
  KEYGEN_JSON=$(SINGPASS_KEYGEN_JSON=1 node scripts/singpass-keygen.mjs .)
  SIG_JWK=$(node -e 'process.stdout.write(JSON.parse(process.argv[1]).SINGPASS_SIG_PRIVATE_JWK)' "$KEYGEN_JSON")
  ENC_JWK=$(node -e 'process.stdout.write(JSON.parse(process.argv[1]).SINGPASS_ENC_PRIVATE_JWK)' "$KEYGEN_JSON")
  write_env SINGPASS_SIG_PRIVATE_JWK "$SIG_JWK"
  write_env SINGPASS_ENC_PRIVATE_JWK "$ENC_JWK"
  say ""
  say "Public JWKS written to $JWKS_FILE (this is the half you give Singpass)."
else
  say "Keeping your existing keys."
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Open your staging app in the Developer Portal"
open_url "$SDP_URL"
step "Log in with Singpass."
step "Top of the dashboard: switch the environment toggle to STAGING."
step "Click your Login / Myinfo (v5) app to open its config page."
say ""
say "Because it's already a v5 app, you keep the same client_id - there's no"
say "need to duplicate it. Only the backend protocol changes."
pause "Press Enter once the app config page is open."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Register your public keys (Token-based Authentication)"
say "Paste the public JWKS below into the app config."
say ""
step "Find the 'Token-based Authentication' field."
step "Choose the JWKS Object option (not JWKS Endpoint)."
step "Paste the JSON below into the box, then Save."
say ""

if [[ -f "$JWKS_FILE" ]]; then
  printf '%s\n' "$DIM"
  cat "$JWKS_FILE"
  printf '%s\n' "$RESET"
  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy < "$JWKS_FILE"
    printf '  %s✓%s Copied to your clipboard.\n' "$GREEN" "$RESET"
  fi
else
  warn "$JWKS_FILE not found - re-run stage 1 to generate it."
fi

say ""
warn "Sanity check before saving: the JSON must contain exactly two keys and"
warn "must NOT contain a \"d\" field anywhere. \"d\" is your private key."
pause "Press Enter once the JWKS is saved."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Set the Redirect URL"
say "This is where Singpass sends the user back after they authenticate."
say "It must match the redirect_uri your backend sends, character for character."
say ""
ask SINGPASS_REDIRECT_URI "Redirect URL to use [http://localhost:3000/api/auth/callback]:"
[[ -z "$SINGPASS_REDIRECT_URI" ]] && SINGPASS_REDIRECT_URI="http://localhost:3000/api/auth/callback"
say ""
step "Paste this into the 'Redirect URL' field in the SDP, then Save:"
say ""
printf '    %s%s%s\n\n' "$BOLD" "$SINGPASS_REDIRECT_URI" "$RESET"
warn "A URL containing an IP address is rejected by Singpass. Use localhost or a hostname."
write_env SINGPASS_REDIRECT_URI "$SINGPASS_REDIRECT_URI"
pause "Press Enter once the Redirect URL is saved."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Select the Allowed Scopes"
say "Tick exactly the Myinfo attributes this app reads. These ten are the"
say "ones lib/myinfo.ts maps onto the loan form:"
say ""
for scope in $DEFAULT_SCOPES; do
  [[ "$scope" == "openid" ]] && continue
  step "$scope"
done
say ""
say "('openid' is implicit and always requested.)"
say ""
warn "In staging you can tick these freely. In production every extra scope"
warn "needs a written justification and Singpass Admin approval - so don't"
warn "tick anything here that the code doesn't actually read."
write_env SINGPASS_SCOPES "$DEFAULT_SCOPES"
pause "Press Enter once the scopes are saved."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Copy your client ID"
say "The SDP shows the client ID on the app config page - a 32-character"
say "alphanumeric string."
say ""
ask SINGPASS_CLIENT_ID "Paste the client ID:"
if [[ ${#SINGPASS_CLIENT_ID} -ne 32 ]]; then
  warn "That's ${#SINGPASS_CLIENT_ID} characters; Singpass client IDs are 32."
  warn "Double-check you copied the client ID and not the app ID."
fi
write_env SINGPASS_CLIENT_ID "$SINGPASS_CLIENT_ID"
write_env SINGPASS_ENV "staging"
write_env SINGPASS_ENABLED "true"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Create a staging test account"
say "Staging has no real Singpass users. You log in with a test account that"
say "carries synthetic Myinfo data."
say ""
step "In the left menu of your staging app, click 'Test Accounts'."
step "Click Create. (You can have up to 5.)"
step "Click the eye icon to reveal the password, and save both somewhere safe."
say ""
say "You'll use this NRIC + password on the Singpass login screen when you"
say "run the flow locally."
say ""
warn "Test account credentials are not secrets worth committing, but don't"
warn "paste them into the repo either."
pause "Press Enter once you have a test account."

finish
